In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.12-py2.py3-none-any.whl (59 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (1.4.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (4.11.1)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.5-cp39-cp39-win_amd64.whl (35 kB)
Requirement already satisfied: requests>=2.26 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (2.27.1)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: numpy>=1.16.5 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (1.21.5)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting lxml>=4.9.1
  Downloading lxml-4.9.2-cp39-cp39-win_amd64.whl (3.9 MB)
Collecting pytz>=2022.5
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
Requirement already satisfied: cryptography>=3.3.2 in c:\users\saite\anaconda3\lib\site-packages (from yfinance) (3.4.8)
Requirement already satisfied: soupsieve>1.2 in c:\users\saite\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)
Requirement already satisfied: cffi>=1.12 in c:\users\saite\anaconda3\lib\site-packages (from cryptography>=3.3.2->yfinance) (1.15.0)
Requirement already satisfied: pycparser in c:\users\saite\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Requirement already satisfied: six>=1.9 in c:\users\saite\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\saite\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\saite\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saite\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\saite\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\saite\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saite\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2021.10.8)
Installing collected packages: pytz, multitasking, lxml, html5lib, frozendict, yfinance
  Attempting uninstall: pytz
    Found existing installation: pytz 2021.3
    Uninstalling pytz-2021.3:
      Successfully uninstalled pytz-2021.3
  Attempting uninstall: lxml
    Found existing installation: lxml 4.8.0
    Uninstalling lxml-4.8.0:
      Successfully uninstalled lxml-4.8.0
Successfully installed frozendict-2.3.5 html5lib-1.1 lxml-4.9.2 multitasking-0.0.11 pytz-2022.7.1 yfinance-0.2.12

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.

In [3]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\saite\anaconda3\lib\site-packages (5.6.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\saite\anaconda3\lib\site-packages (from plotly) (8.0.1)
Requirement already satisfied: six in c:\users\saite\anaconda3\lib\site-packages (from plotly) (1.16.0)

In [4]:
import numpy as np
import pandas as pd
import yfinance as yf
import plotly.graph_objs as go

In [20]:
data = yf.download(tickers = 'UBER',period = '60d',interval = '5m')
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2022-12-21 09:30:00-05:00,25.150000,25.230000,24.959999,24.995001,24.995001,884993
2022-12-21 09:35:00-05:00,24.980000,25.065001,24.870899,24.999901,24.999901,350969
2022-12-21 09:40:00-05:00,24.996000,25.129999,24.940001,25.010000,25.010000,279173
2022-12-21 09:45:00-05:00,25.014999,25.139999,24.972000,25.090799,25.090799,337937
2022-12-21 09:50:00-05:00,25.100000,25.270000,25.035000,25.233200,25.233200,322409
...,...,...,...,...,...,...
2023-03-20 14:10:00-04:00,31.670000,31.700701,31.650000,31.665001,31.665001,70682
2023-03-20 14:15:00-04:00,31.670000,31.705000,31.655001,31.705000,31.705000,48321
2023-03-20 14:20:00-04:00,31.705000,31.770000,31.700001,31.759199,31.759199,83909
2023-03-20 14:25:00-04:00,31.760000,31.764999,31.735001,31.735001,31.735001,51282
2023-03-20 14:30:00-04:00,31.735001,31.735001,31.735001,31.735001,31.735001,0

In [23]:
data.to_csv('UBER.csv')
data

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2022-12-21 09:30:00-05:00,25.150000,25.230000,24.959999,24.995001,24.995001,884993
2022-12-21 09:35:00-05:00,24.980000,25.065001,24.870899,24.999901,24.999901,350969
2022-12-21 09:40:00-05:00,24.996000,25.129999,24.940001,25.010000,25.010000,279173
2022-12-21 09:45:00-05:00,25.014999,25.139999,24.972000,25.090799,25.090799,337937
2022-12-21 09:50:00-05:00,25.100000,25.270000,25.035000,25.233200,25.233200,322409
...,...,...,...,...,...,...
2023-03-20 14:10:00-04:00,31.670000,31.700701,31.650000,31.665001,31.665001,70682
2023-03-20 14:15:00-04:00,31.670000,31.705000,31.655001,31.705000,31.705000,48321
2023-03-20 14:20:00-04:00,31.705000,31.770000,31.700001,31.759199,31.759199,83909
2023-03-20 14:25:00-04:00,31.760000,31.764999,31.735001,31.735001,31.735001,51282
2023-03-20 14:30:00-04:00,31.735001,31.735001,31.735001,31.735001,31.735001,0